### ISSUE TITLE
#### [Groceristar][Grocery][methods]

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/fetch-constants#12]
By using names on methods from this [page](https://groceristar.github.io/documentation/docs/groceristar-website-methods-list/grocery-router/grocery-router.html)
In order to make it better, we'll create set of constants, each for a different method.

Example:
*Method that will Display Grocery List Data*
will became `export const GET_FULL_GROCERY_LIST = "GET_FULL_GROCERY_LIST";`

---

**Comment by akshatphumbhra** [comment]
Hey,

I saw the issue you linked me to, but I wasn't able to understand exactly 
what I needed to do. I created a new file and tried to start, but I'm still 
unsure of what I'm doing. Can you just let me what exactly I'm supposed 
to do?

https://github.com/akshatphumbhra/fetch-constants/commit/070d28ea9f543ceb6653d8f667970aefeec91284

Thanks, 
Akshat Phumbhra

**Comment by atherdon** [comment]
ok, will take a look.
while i'm checking your changes - did you know about git-flow and logic of pull requests?
i have a good set of tutorials, if you need it - tell me

**Comment by atherdon** [comment]
yes, this is what we need.
but we'll have more constants, and i don't like putting everything in one line.
it may be cool, but will be confusing to other people, so please don't save lines :)
export will return object with constants. please continue, and when you'll finish it - open a pull request with your changes.

maybe this task looks simple, but you see - it raise another questions as well

**Comment by akshatphumbhra** [comment]
Hey, Can you send me the tutorials? I'm not very sure about pull requests. 

Thanks

**Comment by atherdon** [comment]
https://github.com/ChickenKyiv/awesome-git-article#forking-pull-requests

**Comment by atherdon** [comment]
please confirm that we cover all methods from grocery router - so i can close this task

**Comment by akshatphumbhra** [comment]
Yes, I've covered all the methods from Grocery Router.


Thanks,
Akshat Phumbhra

**Comment by atherdon** [comment]
perfect, closing it
