### ISSUE TITLE
 #### [Groceristar][Ingredients][methods]

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/fetch-constants#15]
By using names on methods from this [page](https://groceristar.github.io/documentation/docs/groceristar-website-methods-list/ingredients-router/ingredients-router.html)
In order to make it better, we'll create set of constants, each for a different method.

Example:
*Create or find at db new ingredient new ingredient and attach it to grocery list*
will became `export const FIND_OR_CREATE_AND_ATTACH_TO_GROCERY = "FIND_OR_CREATE_AND_ATTACH_TO_GROCERY";`

**Comment by atherdon** [comment]
@akshatphumbhra how things going? do you need help with this task?

**Comment by akshatphumbhra** [comment]
Hey,

Sorry things are a little slow. I'm actually in college and have a lot
to catch up on. I might be slow for a little while. But over the summer,
I'll pick up. I apologize for the inconvenience.


Thanking you,
Akshat Phumbhra

**Comment by atherdon** [comment]
not a problem, take your time. just tell me a preliminary day when you'll be able to complete it, so i can plan my work with other interns too

**Comment by akshatphumbhra** [comment]
So I can start working now, but I can't say how long it'll take me. I'm not
sure how hectic my schedule is. But once summer starts, I'll be on it the
whole time. So by June 1st, I'll finish everything.

Thanks,
Akshat Phumbhra

**Comment by atherdon** [comment]
let's go this way. if you'll have time before june - then work on some tasks, that i assign to you. But if i'll have someone else - i'll assign your task to them, in order to move it quickly. tell me if this ok for you

**Comment by akshatphumbhra** [comment]
Yes, that works for me. Thanks so much for accommodating me.


Best,
Akshat Phumbhra
