### ISSUE TITLE
#### [Recipe Search][URLS][part1]

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/fetch-constants#21]
https://chickenkyiv.github.io/search-api-documentation/docs/db-schema

https://chickenkyiv.github.io/search-api-documentation/docs/db-schema
By using names on URLS from this [page](https://chickenkyiv.github.io/search-api-documentation/docs/database-tables-models/attribute/allergy)
In order to make it better, we'll create set of constants, each for a different method.

Example:
*http://localhost:3000/api/attribute?filter[where][type]=allergy*
will became `export const ATTRIBUTE_FILTER_TYPE_ALLERGY = "ATTRIBUTE_FILTER_TYPE_ALLERGY";`

**Comment by atherdon** [comment]
@shortcuter4 will add you as team member to our github organization after completion of a few first tasks.

**Comment by shortcuter4** [comment]
@atherdon 
What is your suggestion - > Shall I start with reading this doc :
https://groceristar.github.io/documentation/
or
https://github.com/GroceriStar/fetch-constants
in order to understand the issue and beginning to figure out problem solution

**Comment by atherdon** [comment]
my suggestion will be to re-read description of this task and focus on questions related to this task.
For sure, i can give you more details about the project, etc. But my goal is your practice and real experience.
Tell me what exactly is not clear for you at this task and i'll explain

**Comment by atherdon** [comment]
@shortcuter4 how its going with this task? can you push changes that you have so far?

**Comment by shortcuter4** [comment]
@atherdon honestly, not , but do not misunderstand me, because I have been very busy days since then such as 1 project, 2 labs, 2 midterms and 2 homework deadlines during the week at university, and I should handle to finish them as well. 
If you give me more time, I will do my best to try handling this problem.

**Comment by atherdon** [comment]
ok, no problem. again - if it's hard task - then you should ask more questions. because main reason of this task is about setup a workflow, not about learning how our project works. I mean we'll handle that later.

**Comment by shortcuter4** [comment]
that's true. and can you clarify please, what did you mean by mentioning "re-read description of this task" ? I was not sure if I had read the description you mentioned. did you mean the description in the link below ? 
https://github.com/GroceriStar/fetch-constants/
or this one : 
https://groceristar.github.io/documentation/ 
(or both?)
I think, I had a difficulty to understand the task itself even though example was given, in other words, what was the issue in the 'issue' description
