### ISSUE TITLE
#### [Groceristar][Favorites][methods]

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/fetch-constants#3]
By using names on methods from this [page](https://groceristar.github.io/documentation/docs/groceristar-website-methods-list/favorite-router/favorite-router.html)
In order to make it better, we'll create a set of constants, each for a different method.

Example:
*Get All ingredients with status favorite*
will became `export const GET_ALL_FAVORITE_INGREDIENTS = "GET_ALL_FAVORITE_INGREDIENTS ";`

**Comment by kursadcayir** [comment]
for Delete ingredients from favorites list , export const DELETE__FAVORITE_INGREDIENTS_IN_LIST = "DELETE__FAVORITE_INGREDIENTS_IN_LIST";

**Comment by kursadcayir** [comment]
for addition of color , 
export const INGREDIENT_ADD_FAVORITE_COLOR = "INGREDIENT_ADD_FAVORITE_COLOR ";

for clearing the color 
export const INGREDIENT_CLEARING_COLOR = "ADD_FAVORITE_COLOR ";

**Comment by kursadcayir** [comment]
for method that list all favorites;
export cons LIST_FAVORıTES= "LIST_FAVORıTES ";

**Comment by atherdon** [comment]
it's a question?

**Comment by kursadcayir** [comment]
Actually , I did not understand what to do . Do I need to implement these variables in table ?

**Comment by atherdon** [comment]
you need to create a file, with variables and open a pull request with your
changes. when i'll see the whole code - i'll tell you my comments

**Comment by kursadcayir** [comment]
Sorry. I think that I am gonig to implement documentation. my bad .

**Comment by atherdon** [comment]
not a problem at all. do you know how to contribute to github repositories? i have a good tutorial for that - just tell me if you need it

**Comment by atherdon** [comment]
@kursadcayir how its going with this task? can you push changes that you have so far?

**Comment by kursadcayir** [comment]
Hi ,
I did not focus on much about graph ql , because of the job search . I will try to push in this week .

**Comment by atherdon** [comment]
you can tell me if you busy - it's ok, and i'll move this task to someone else

**Comment by atherdon** [comment]
just have an idea - maybe i need to share your linkedin profile at my network - maybe it will help you?

**Comment by atherdon** [comment]
tell me what do you think
