### ISSUE TITLE
finish contant departments

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/fetch-constants#39]
By using names on methods from this [page](https://groceristar.github.io/documentation/docs/groceristar-website-methods-list/department-router/department-router.html) we created a set of constants.
Each constant is just a human version of method that we have. But we didn't finish work, related to department methods. You'll need to do it.

Example:
*Get data, related to single department*
equal to `export const GET_DEPARTMENT_DATA = "GET_DEPARTMENT_DATA";`

- [x] you need to move your file at Groceristar folder(decide where exactly it should be - or discuss with me)
- [x] rename this file, because it's not very clear name.
- [x] we need it as JS file

I assume that file https://github.com/GroceriStar/fetch-constants/blob/master/constants is related to department routes. we need to remove it and confirm that we actually can connect to that file from other file and be able to access to all of that constants

**Comment by atherdon** [comment]
#12 #17 #15

**Comment by atherdon** [comment]
@elnur004

**Comment by elnur004** [comment]
i guess i couldn't understand this task properly and actually don't know exactly what to do. can you explain a little more?

**Comment by atherdon** [comment]
ok, let's start from the first part.
1) did you find a file, right?
2) did you fork this repository and be able to work on it locally?
3) did you find a `Groceristar` folder at this project?

**Comment by elnur004** [comment]
ok. i find

**Comment by elnur004** [comment]
i've done two examples, but don't know are true or not

**Comment by atherdon** [comment]
please commit your changes to your forked repo and later open a pull request, so i'll be able to take a look

**Comment by atherdon** [comment]
if what i'm talking about is not clear - tell me and i'll give you a qiuck tutorial about how to use git + github

**Comment by elnur004** [comment]
may you give that tutorial please?

**Comment by atherdon** [comment]
sure, but i have another idea. i think we need to reduce pace and go slowly

**Comment by atherdon** [comment]
check this task, i think it's very simple: https://github.com/ChickenKyiv/awesome-dev-stuff/issues/8

**Comment by atherdon** [comment]
ok, i think we have one last item todo and i'll be able to close this task

**Comment by elnur004** [comment]
where should i move this folder? do you have any suggestion for me?

**Comment by atherdon** [comment]
here is a place, where code, related to this functionality should be stored: https://github.com/GroceriStar/fetch-constants/tree/master/src/Groceristar/api

**Comment by atherdon** [comment]
closing it. please jump into awesome-dev-stuff task
